version: '3.7'

networks:
  localdev:
    name: localdev

services:
  backend:
    container_name: 'modern-crusaders-backend'
    build: './'
    ports:
      - "7070:8080"
    networks:
      - localdev

  frontend:
    container_name: 'modern-crusaders-frontend'
    build: './SocialMediaAnalysis.UI'
    ports:
      - 8080:4200
    networks:
      - localdev
